services:

    analytics:
        extends:
            file: ./app.yml
            service: app
        networks:
            internal:
                aliases:
                    - analysis.docker.local

        logging:
            driver: syslog
            options:
                tag: docker-analysis
        restart: unless-stopped       
networks:
    internal:
        name: shoestring-internal
