services:

    analytics:

        image: nodered/node-red:3.0.2

        volumes:
          - ./data:/data:rw
          - ./config:/config:ro

        ports:
          - "1880:1880"
    
        networks:
            internal:
                aliases:
                    - analysis.docker.local

        logging:
            driver: syslog
            options:
                tag: docker-analysis
                
        restart: unless-stopped